INSERT INTO cities(name) VALUES
 ('NYC')
,('Reims')
,('Paris')
,('Pasadena')
,('San Francisco')
,('Burlingame')
,('Lille')
,('Bergen')
,('Melbourne')
,('Newark')
,('Bridgewater')
,('Nantes')
,('Cambridge')
,('Helsinki')
,('Stavern')
,('Allentown')
,('Salzburg')
,('Chatswood')
,('New Bedford')
,('Liverpool')
,('Madrid')
,('Lule')
,('Singapore')
,('South Brisbane')
,('Philadelphia')
,('Lyon')
,('Vancouver')
,('Burbank')
,('New Haven')
,('Minato-ku')
,('Torino')
,('Boras')
,('Versailles')
,('San Rafael')
,('Nashua')
,('Brickhaven')
,('North Sydney')
,('Montreal')
,('Osaka')
,('White Plains')
,('Kobenhavn')
,('London')
,('Toulouse')
,('Barcelona')
,('Los Angeles')
,('San Diego')
,('Bruxelles')
,('Tsawassen')
,('Boston')
,('Cowes');
INSERT INTO cities(name) VALUES
 ('Oulu')
,('San Jose')
,('Graz')
,('Makati City')
,('Marseille')
,('Koln')
,('Gensve')
,('Reggio Emilia')
,('Frankfurt')
,('Espoo')
,('Dublin')
,('Manchester')
,('Aaarhus')
,('Glendale')
,('Sevilla')
,('Brisbane')
,('Strasbourg')
,('Las Vegas')
,('Oslo')
,('Bergamo')
,('Glen Waverly')
,('Munich')
,('Charleroi');
